export default {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  UPDATE_QUANTITY: 'UPDATE_QUANTITY',
  CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
  CHECKOUT_FAILURE: 'CHECKOUT_FAILURE',
  TOGGLE_FINANCE: 'TOGGLE_FINANCE',
  SELECT_SUBSCRIPTION_TYPE: 'SELECT_SUBSCRIPTION_TYPE',
};
