export default {
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  ADD_TO_CART: 'ADD_TO_CART',
  MOVE_CART_TO_ORDERED: 'MOVE_CART_TO_ORDERED',
  UPDATE_QUANTITY: 'UPDATE_QUANTITY',
  SELECT_SUBSCRIPTION_TYPE: 'SELECT_SUBSCRIPTION_TYPE',
};
